# Generated by Django 3.2.8 on 2021-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211031_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetails',
            name='per_gpa_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
