# Generated by Django 3.2.8 on 2021-11-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_educationdetails_per_gpa_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetails',
            name='local_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
