# Generated by Django 3.2.8 on 2021-11-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_addressdetails_local_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetails',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
