# Generated by Django 3.2.8 on 2021-11-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_addressdetails_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetails',
            name='institution_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='faculty',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
