# Generated by Django 3.2.8 on 2021-11-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211110_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedetails',
            name='is_current',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
